name: mlflow-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip
  - pip:
      - mlflow==3.6.0
      - scikit-learn==1.4.2
      - pandas==2.3.3
      - numpy==2.3.5
      - scikit-optimize==0.10.2
      - matplotlib==3.10.7
      - seaborn==0.12.3
      - requests==2.31.0
      - docker==7.1.0
      - rclone==1.62.2
