name: diabetes-mlflow-project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - scikit-learn=1.3.0
  - pandas=2.0.3
  - numpy=1.24.3
  - matplotlib=3.7.1
  - scikit-optimize=0.9.0
  - joblib=1.3.0
  - pyyaml=6.0
  - pip:
    - mlflow>=2.8.1