name: mlflow-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip
  - pip:
      - mlflow==3.6.0
      - scikit-learn==1.4.2
      - pandas==2.3.3
      - numpy==2.3.5
      - scikit-optimize==0.10.2
      - matplotlib==3.10.7
      - seaborn==0.12.2
      - joblib==1.5.2
      - Flask==3.1.2
      - Flask-CORS==6.0.1
      - docker==7.1.0
      - fastapi==0.121.3
      - dagshub==0.6.0  # <- tambahkan ini
